### ISSUE TITLE
Add option to disable vagrant-cachier

### ISSUE THREAD

**Issue by greg-hellings** [ansible-community/molecule-vagrant#100]
Currently the generated Vagrantfile checks for the presence of the cachier plugin, and configures it if it is found.

However, it's very possible that this plugin could be installed on some hosts, but not others, and a user might want to explicitly disable this. Provide an option to allow that.

**Comment by apatard** [comment]
When working on the vagrant.yml removal thing, I've not dealt with cachier because it was an unrelated change but I had this plugin in my mind for quite some time.

At minimum, making it optional is a good idea, but I've been wondering about doing more than that. Cachier has not been maintained for quite some time (https://github.com/fgrehm/vagrant-cachier/issues/143) so I'm even wondering if it's still working correctly
