### ISSUE TITLE
Reusing vagrant instance for different roles

### ISSUE THREAD

**Issue by vkmellon** [ansible-community/molecule-vagrant#32]
Looks like we can't reuse instance with different roles.
Example structure: 
```
/roles/role1
/roles/role2
```
Example converge:
role1:
```
$cd /roles/role1
$molecule converge
```
Output:
```
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [Create molecule instance(s)] *********************************************
    changed: [localhost] => (item=instance)
```
role2:
```
$cd /roles/role2
$molecule converge
Output:
```
```
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [Create molecule instance(s)] *********************************************
    changed: [localhost] => (item=instance)
```

Get list of instances:

`$vagrant global-status`

```
 id       name        provider   state   directory                                               
------------------------------------------------------------------------------------------------
3dc4605  instance virtualbox running /home/user/.cache/molecule/role1/default  
6a6bed2  instance virtualbox running /home/user/.cache/molecule/role2/default
```

Expected result:
On second role
```
--> Action: 'create'
Skipping, instances already created.
```

**Comment by JamesWrigley** [comment]
That's how Molecule works, each scenario gets its own instance. If you want to test multiple roles with the same instance you'd have to modify your scenarios `converge.yml` to apply `role1` and `role2`. I don't believe this is `molecule-vagrant` specific.

**Comment by vkmellon** [comment]
With docker molecule is reusing the same container

**Comment by JamesWrigley** [comment]
I'm guessing that's because the instances for each role have the same name (`instance`), rather than by design.

**Comment by apatard** [comment]
In docker, the instance name is the container name. This means that if someone is using the same instance name on every molecule scenario, they may be using the same molecule container.

With vagrant, the instance name is used as a name to designate the VM in vagrant, as in docker. The difference is that the vagrant VM name is not the VM name as known by virtualbox/libvirt/...:
https://www.vagrantup.com/docs/providers/virtualbox/configuration:
```
By default, Vagrant sets it to the containing folder of the Vagrantfile plus
a timestamp of when the machine was created.
```
https://github.com/vagrant-libvirt/vagrant-libvirt#libvirt-configuration:
```
The default Libvirt guest name becomes a concatenation of
the <current_directory>_<guest_name>
```
As said by @JamesWrigley , with molecule, each scenario is supposed to be using its own instance and not using an existing instance. It's possibly not by design that what you try to achieve is working.

I'm not even sure to understand what you're trying to achieve tbh. If role2 needs that the instance is setup by role1, as in role1 provide a service and role2 is configuring the customer, personnaly, I would add role1 to ``requirements.yml`` and use role1 in the ``prepare.yml``.

If you really want to reuse the same instance, you can try modifying the scenario's playbook as suggested in previous comments or maybe trying using ``instance_raw_config_args`` like this (**untested**):
```
platforms:
- name: myinstance
  instance_raw_config_args:
  - 'vm.name = myinstance'
```
but I guess vagrant will return an error when you'll converge role2.

**Comment by ssbarnea** [comment]
That use-case is outside the scope of the driver or even molecule. I would like to recommend you to use discussions https://github.com/ansible-community/molecule/discussions 

You can use molecule to test whatever you want, is not specific to a single role. Still about sharing instances between multiple scenarios, ask on discussions.
