### ISSUE TITLE
Broken CI with CentOS 8.2

### ISSUE THREAD

**Issue by apatard** [ansible-community/molecule-vagrant#37]
The CI is currently broken on CentOS 8.2 due to missing symbols in the OpenSSL libs bundled with vagrant rpm.
There's a bug opened in vagrant git (https://github.com/hashicorp/vagrant/issues/11020) but it seems that only workarounds
are discussed. I ended implementing them in https://github.com/apatard/molecule-vagrant/tree/centos82-ssl but it's still
a hack so I prefer discussing the issue here before creating a merge request.
This may ends with a better solution that this commit.

**Comment by ssbarnea** [comment]
You discovered one of the reasons why Vagrant is not a core plugin anymore: Hashicorp inability to provide ready to use YUM repositories for current operating systems. Hopefully someone from them reads this and takes action.

You are welcomed to implement whatever hack you want/need in order to keep it working. Just be sure you mention reasons in comments with upstream bug links, feel tree to open new bug for centos-8.2 on vagrant itself, old ticket may be already lost-in-time.

I seen that you already included link, so you already master the process :)

**Comment by apatard** [comment]
Ok. I'll submit a PR with my change. I hope that it'll work fine in CI but failure is stil possible. The official centos 8.2 libvirt vagrant box I've used is possibly not the same environment as the one used by the CI.
In the long time, yeah, would be nice to get the rpm fixed but I don't have high hopes. If I believe the different bug reports in vagrant and vagrant-libvirt, the rpm is broken en fedora 30+ and now centos 8.2, which means it has been broken for nearly one year.

**Comment by apatard** [comment]
CI on Centos 8.2 should be fixed with PR39, so I'm closing my own bug.
